### ISSUE TITLE
Alternate Approaches for the Julia code

### ISSUE THREAD

**Issue by alecloudenback** [actuarialopensource/benchmarks#1]
Thanks for putting this together. I looked at the Julia code and keeping the calculation apples-to-apples (i.e. including the allocation of the mortality tables into an array), it could be up to ~7.3 faster than the current benchmark ("baseline"). In essence, the code is running fast enough that strategies to reduce the memory allocations are impactful in the average runtime. It's also perhaps more idiomatic Julia code (Python (numpy) encourages you to put everything into arrays first, that's not needed in Julia).

I also included an example showing using [LifeContingencies.jl](https://github.com/JuliaActuary/LifeContingencies.jl) and [Yields.jl](https://github.com/JuliaActuary/Yields.jl) to handle to decrements and discounting. This version is about 0.3x times as fast as the baseline, probably indicating that I could design some mutable structs into LifeContingencies to avoid needing to re-allocate across different sets of mortality rates.

| benchmark                       | incl table allocation | mean time (absolute) | times faster |
|---------------------------------|-----------------------|----------------------|--------------|
| baseline                        | yes                   | 1810μs               | 1x           |
| mapreduce for                   | yes                   | 325μs                | 5.6x         |
| mapreduce for                   | no                    | 325μs                | 7.7x         |
| nested for loop                 | yes                   | 247μs                | 7.3x         |
| nested for loop                 | no                    | 160μs                | 11.3x        |
| LifeContigencies.jl + Yields.jl | yes                   | 6854μs               | 0.3x         |

Here's the Pluto notebook:

https://gist.github.com/alecloudenback/e3dc7802a49b9d2f5e108cf322fb2e0b

**Comment by MatthewCaseres** [comment]
Maybe it would be more general to say something like `unit_claims = npx .* q` and end the calculation right there? Here is my justification for the proposed change to the benchmark.

Having a `unit_claims` tensor will simplify any calculation that needs this sort of tensor down the line, so while it costs something up front, I view it as an investment in the speed of future calculations which are performed interactively and perhaps more often, as well as developer ergonomics.

Basically, I think we want all the information for every policy at every point in time, represented by tensors of shape 
* `(policies,)` for policy information like face amount, initial duration
* `(timesteps)` for information like economic scenarios
* `(policies, timesteps)` for things like unit claims

Without information for each policy at each point in time, I do not think we are providing the user with everything they could possibly want to know. It may cost memory/time to create such tensors, but I think it is necessary. Larger workloads can be calculated in batch or in parallel.

To recap:
* Proposal to change benchmark to the creation of an array and not a reduction over an array
* Design ideas for term life modeling software

Does this sound reasonable?

**Comment by MatthewCaseres** [comment]
I think I had too strong an opinion on how to write the code.

I'm going to break up this benchmark into two benchmarks.

**Comment by MatthewCaseres** [comment]
Benchmark now uses 8 threads and the nested for loop approach (it is fastest).

It does include table allocation. In the future maybe I will split the benchmark, in which case there will be separate benchmarks for

1. allocating the tables
2. doing the calculation
