### ISSUE TITLE
A lot of type instability in the Term Bechmark for Julia

### ISSUE THREAD

**Issue by alecloudenback** [actuarialopensource/benchmarks#24]
Quickly looked at this.... Memoization makes it difficult to pin down, but there's a lot of runtime dispatch happening because of functions potentially returning `Any`

**Comment by alecloudenback** [comment]
Partially fixed in #25

**Comment by serenity4** [comment]
I don't think there is anything concrete to address now. We can always look at type instability if we want to have another round of performance optimization, but right now performance has already been optimized quite a bit.

Feel free to reopen this if you have any concrete example in mind where type instability occurs in a way that affects performance.
