### ISSUE TITLE
How to generate per policy results with basicterm_scratch.py?

### ISSUE THREAD

**Issue by acturtle** [actuarialopensource/benchmarks#40]
I'd like to produce the results of the `basicterm_scratch.py` script but I'd like to have `pv_net_cf` for each model point separately (and not aggregated). I need that because individual results help with the reconciliation.

Is there a way to produce individual results?

**Comment by MatthewCaseres** [comment]
I believe that if you call the function like 

```py
from basicterm_scratch import pv_net_cf

pv_net_cf()
```

This is a vector of length 10,000 and is not aggregated?

**Comment by MatthewCaseres** [comment]
Closing this, will reopen if the question is not answered fully and requires code changes
